### ISSUE TITLE
Member function being repeated with 'hidden'

### ISSUE THREAD

**Issue by ned14** [foonathan/standardese#101]
If you look at https://ned14.github.io/outcome/reference/success_failure/, you'll see value() and error() repeated e.g.

```c++
    //=== value ===//
    constexpr value_type& value() &;
    constexpr value_type& value() const &;
    constexpr value_type&& value() &&;
    constexpr value_type&& value() const &&;
    constexpr 'hidden'& value() &;
    constexpr 'hidden'& value() const &;
    constexpr 'hidden'&& value() &&;
    constexpr 'hidden'&& value() const &&;
```

Same goes later for error() and exception() in the other type sugars. Weird eh?

**Comment by foonathan** [comment]
Yes, weird

**Comment by foonathan** [comment]
Fixed this one, group names weren't considered unique before.

**Comment by foonathan** [comment]
The temporary branch 'outcome-fixes' contains standardese with those fixes applied.

**Comment by ned14** [comment]
The problem still appears on https://ned14.github.io/outcome/reference/success_failure/

Do I need to make the group names unique?

**Comment by foonathan** [comment]
You don't seem to be using the outcome-fixes branches, anchors are still the old ones.

**Comment by ned14** [comment]
Also looks to be fixed, though I have some cleanup to do.

So I'll freeze everything tonight I think, tomorrow open issues for all problems I know of, and we'll let things rip on Friday. Thanks Jonathan.
